import type { DrawerState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: DrawerState, fileName = "drawer"): ExportPayload {
  return { fileName: `${fileName || "drawer"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: DrawerState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "function getClosedTransform(s) {",
    "  if (s.animationType === \"fade\") return \"translate(0,0)\";",
    "  if (s.animationType === \"scale\") return \"scale(0.96)\";",
    "  if (s.side === \"left\") return \"translateX(-100%)\";",
    "  if (s.side === \"right\") return \"translateX(100%)\";",
    "  if (s.side === \"top\") return \"translateY(-100%)\";",
    "  return \"translateY(100%)\";",
    "}",
    "function overlayColor(s) {",
    "  if (!/^#[0-9a-fA-F]{6}$/.test(s.overlayBg)) return s.overlayBg;",
    "  return s.overlayBg + Math.round(Math.max(0, Math.min(1, s.overlayOpacity)) * 255).toString(16).padStart(2, \"0\");",
    "}",
    "",
    "export default function DrawerComponent({ open, defaultOpen = state.defaultOpen ?? state.previewState === \"open\", onOpenChange } = {}) {",
    "  const isControlled = open !== undefined;",
    "  const [internalOpen, setInternalOpen] = React.useState(defaultOpen);",
    "  const [closeHover, setCloseHover] = React.useState(false);",
    "  const isOpen = isControlled ? open : internalOpen;",
    "  const triggerRef = React.useRef(null);",
    "  const titleId = `${state.id}-title`;",
    "  const descriptionId = `${state.id}-description`;",
    "  const setOpen = React.useCallback((nextOpen) => {",
    "    if (!isControlled) setInternalOpen(nextOpen);",
    "    onOpenChange?.(nextOpen);",
    "    if (!nextOpen && state.focusReturn) requestAnimationFrame(() => triggerRef.current?.focus());",
    "  }, [isControlled, onOpenChange]);",
    "  React.useEffect(() => {",
    "    if (!isOpen || !state.closeOnEscape) return;",
    "    const onKeyDown = (event) => { if (event.key === \"Escape\") setOpen(false); };",
    "    document.addEventListener(\"keydown\", onKeyDown);",
    "    return () => document.removeEventListener(\"keydown\", onKeyDown);",
    "  }, [isOpen, setOpen]);",
    "  const horizontal = state.side === \"left\" || state.side === \"right\";",
    "  const panelStyle = {",
    "    position: \"fixed\",",
    "    top: state.side === \"bottom\" ? \"auto\" : 0,",
    "    right: state.side === \"left\" ? \"auto\" : 0,",
    "    bottom: state.side === \"top\" ? \"auto\" : 0,",
    "    left: state.side === \"right\" ? \"auto\" : 0,",
    "    width: horizontal ? state.width : \"100%\",",
    "    maxWidth: \"calc(100vw - 24px)\",",
    "    height: horizontal ? \"100%\" : state.height,",
    "    minHeight: horizontal ? \"100%\" : state.height,",
    "    display: \"grid\",",
    "    gridTemplateRows: \"auto 1fr auto\",",
    "    overflow: \"hidden\",",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "        boxShadow: buildShadow(state),",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    opacity: state.disabled ? (state.disabledOpacity ?? 0.5) : (isOpen ? 1 : (state.animationType === \"fade\" ? 0 : 1)),",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    zIndex: 50,",
    "    transform: isOpen ? \"translate(0,0)\" : getClosedTransform(state),",
    "    transition: state.transitionDuration > 0 ? \"transform 320ms cubic-bezier(.32,.72,0,1), opacity 320ms ease\" : \"none\"",
    "  };",
    "  const overlayStyle = {",
    "    position: \"fixed\",",
    "    inset: 0,",
    "    zIndex: 40,",
    "    pointerEvents: isOpen ? \"auto\" : \"none\",",
    "    background: isOpen && state.showOverlay ? overlayColor(state) : \"transparent\",",
    "    transition: state.transitionDuration > 0 ? \"background 320ms ease\" : \"none\"",
    "  };",
    "  return (",
    "    <div id={state.id}>",
    "      <button ref={triggerRef} type=\"button\" disabled={state.disabled} onClick={() => setOpen(true)}>",
    "        {state.triggerLabel || \"Open drawer\"}",
    "      </button>",
    "      <div",
    "        onMouseDown={(event) => { if (isOpen && state.closeOnOutside && event.target === event.currentTarget) setOpen(false); }}",
    "        style={overlayStyle}",
    "      >",
    "        <section role=\"dialog\" aria-modal={state.modal} aria-label={state.ariaLabel} aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={state.tabIndex} style={panelStyle}>",
    "          <header style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", padding: state.padding, background: state.headerBg, color: state.headerText, borderBottom: `1px solid ${state.headerBorder}` }}>",
    "            <h2 id={titleId} style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "            <button type=\"button\" aria-label=\"Close drawer\" onClick={() => setOpen(false)} onMouseEnter={() => setCloseHover(true)} onMouseLeave={() => setCloseHover(false)} style={{ display: \"grid\", placeItems: \"center\", width: state.closeIconSize + 16, height: state.closeIconSize + 16, border: 0, borderRadius: 999, background: closeHover ? state.closeIconHoverBg : \"transparent\", color: state.closeIconColor, cursor: \"pointer\" }}>",
    "              <svg aria-hidden=\"true\" width={state.closeIconSize} height={state.closeIconSize} viewBox=\"0 0 16 16\" fill=\"none\"><path d=\"M4 4l8 8M12 4l-8 8\" stroke=\"currentColor\" strokeWidth=\"1.6\" strokeLinecap=\"round\" /></svg>",
    "            </button>",
    "          </header>",
    "          <div style={{ padding: state.padding, display: \"grid\", gap: state.gap, position: \"relative\" }}>",
    "            {state.handleVisible && !horizontal ? <span aria-hidden=\"true\" style={{ position: \"absolute\", top: 6, left: \"50%\", transform: \"translateX(-50%)\", width: state.handleWidth, height: 4, borderRadius: 999, background: state.handleColor }} /> : null}",
    "            {state.handleVisible && horizontal ? <span aria-hidden=\"true\" style={{ position: \"absolute\", top: \"50%\", [state.side === \"left\" ? \"right\" : \"left\"]: 6, transform: \"translateY(-50%)\", width: 4, height: state.handleWidth, borderRadius: 999, background: state.handleColor }} /> : null}",
    "            <p id={descriptionId} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "            <div style={{ height: 1, background: state.dividerColor }} />",
    "            <p style={{ margin: 0, color: state.muted, fontSize: 12 }}>{state.helper} Focus trap is not implemented; focus return is {state.focusReturn ? \"enabled\" : \"disabled\"}.</p>",
    "          </div>",
    "          <footer style={{ display: \"flex\", flexWrap: \"wrap\", justifyContent: \"flex-end\", gap: 8, padding: state.padding, background: state.footerBg, borderTop: `1px solid ${state.footerBorder}` }}>",
    "            <button type=\"button\" style={{ borderRadius: 12, padding: \"8px 16px\", border: 0, background: state.primaryBg, color: state.primaryText, cursor: \"pointer\" }}>{state.label}</button>",
    "            <button type=\"button\" style={{ borderRadius: 12, padding: \"8px 16px\", background: state.secondaryBg, color: state.secondaryText, border: `1px solid ${state.secondaryBorder}`, cursor: \"pointer\" }}>Cancel</button>",
    "          </footer>",
    "        </section>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}
