import type { DrawerState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: DrawerState, fileName = "drawer"): ExportPayload {
  return { fileName: `${fileName || "drawer"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: DrawerState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "export default function DrawerComponent({ open, defaultOpen = state.defaultOpen ?? state.previewState === \"open\", onOpenChange } = {}) {",
    "  const isControlled = open !== undefined;",
    "  const [internalOpen, setInternalOpen] = React.useState(defaultOpen);",
    "  const isOpen = isControlled ? open : internalOpen;",
    "  const triggerRef = React.useRef(null);",
    "  const titleId = `${state.id}-title`;",
    "  const descriptionId = `${state.id}-description`;",
    "  const setOpen = React.useCallback((nextOpen) => {",
    "    if (!isControlled) setInternalOpen(nextOpen);",
    "    onOpenChange?.(nextOpen);",
    "    if (!nextOpen && state.focusReturn) requestAnimationFrame(() => triggerRef.current?.focus());",
    "  }, [isControlled, onOpenChange]);",
    "  React.useEffect(() => {",
    "    if (!isOpen || !state.closeOnEscape) return;",
    "    const onKeyDown = (event) => { if (event.key === \"Escape\") setOpen(false); };",
    "    document.addEventListener(\"keydown\", onKeyDown);",
    "    return () => document.removeEventListener(\"keydown\", onKeyDown);",
    "  }, [isOpen, setOpen]);",
    "  const horizontal = state.side === \"left\" || state.side === \"right\";",
    "  const panelStyle = {",
    "    position: \"fixed\",",
    "    top: state.side === \"bottom\" ? \"auto\" : 0,",
    "    right: state.side === \"left\" ? \"auto\" : 0,",
    "    bottom: state.side === \"top\" ? \"auto\" : 0,",
    "    left: state.side === \"right\" ? \"auto\" : 0,",
    "    width: horizontal ? state.width : \"100%\",",
    "    maxWidth: \"calc(100vw - 24px)\",",
    "    height: horizontal ? \"100%\" : state.height,",
    "    minHeight: horizontal ? \"100%\" : state.height,",
    "    padding: state.padding,",
    "    display: \"grid\",",
    "    alignContent: \"start\",",
    "    gap: state.gap,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px solid ${state.border}`,",
    "    boxShadow: `0 ${Math.round(state.shadow / 3)}px ${state.shadow}px rgba(0,0,0,.28)`,",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: state.fontFamily,",
    "    zIndex: 50",
    "  };",
    "  return (",
    "    <div id={state.id}>",
    "      <button ref={triggerRef} type=\"button\" disabled={state.disabled} onClick={() => setOpen(true)}>",
    "        {state.triggerLabel || \"Open drawer\"}",
    "      </button>",
    "      {isOpen && (",
    "        <div",
    "          aria-hidden={false}",
    "          onMouseDown={(event) => { if (state.closeOnOutside && event.target === event.currentTarget) setOpen(false); }}",
    "          style={{ position: \"fixed\", inset: 0, zIndex: 40, background: state.showOverlay ? \"rgba(15, 23, 42, .58)\" : \"transparent\" }}",
    "        >",
    "          <section role=\"dialog\" aria-modal={state.modal} aria-label={state.ariaLabel} aria-labelledby={titleId} aria-describedby={descriptionId} tabIndex={state.tabIndex} style={panelStyle}>",
    "            <button type=\"button\" aria-label=\"Close drawer\" onClick={() => setOpen(false)} style={{ justifySelf: \"end\" }}>Close</button>",
    "            <h2 id={titleId} style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h2>",
    "            <p id={descriptionId} style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "            <div style={{ display: \"flex\", flexWrap: \"wrap\", gap: 8 }}><button type=\"button\">{state.label}</button><button type=\"button\">Cancel</button></div>",
    "            <p style={{ margin: 0, color: state.muted, fontSize: 12 }}>{state.helper} Focus trap is not implemented; focus return is {state.focusReturn ? \"enabled\" : \"disabled\"}.</p>",
    "          </section>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}
